modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
#issueTrackerURL=""

[[mods]]
modId="overlayhack"
version="${file.jarVersion}"
displayName="Overlayhack"
#updateJSONURL=""
authors="Grimmauld"
description='''
Some hacks based on FML'''

[[dependencies.overlayhack]]
modId="forge"
mandatory=true
versionRange="[36.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.overlayhack]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"